librariesio/depper

main.go

This looks like the official way to fork the logs: https://github.com/sirupsen/logrus/blob/d131c24e23baaa812461202af6d7cfa388e2d292/hooks/writer/README.md#usage
https://app.clubhouse.io/tidelift/story/15442/depper-more-consistent-logging

Make sure we send good logs to stdout and bad logs to stderr.

---

main.go

One thing I missed from the hooks docs! Fixes this duplicate logging:
https://app.clubhouse.io/tidelift/story/15442/depper-more-consistent-logging

Quickfix for stdout/stderr log forking.

---

ingestors/elm.go
ingestors/npm.go
ingestors/rubygems.go

Removing ingestion logging in individual ingestors. If we _want_ to do something to log these we can do them at a higher level, but I think for now the logging publisher gets us what we need.

Removed logging from ingestors directly

---

ingestors/npm.go
publishers/sidekiq.go
redis/redis.go

Extract a `redis` package with a `redis.Client` global variable we can use for all redis-y things in Depper.
We don't need to setup a pool because the redis library already does this by default, with reasonable default settings (10 connections per CPU, by default, etc).

Extract redis to service-wide global connection pool.

---

ingestors/nuget.go
main.go

* save the last most-recently-updated 4 pages of package names to redis
* sync the last most-recently-updated 3 pages of packages
* sync all package versions updated >= LatestRun (defaults to 1.day.ago)
```
...
time="2021-01-28T11:29:54-05:00" level=info msg="Depper publish" name=LykkeBiz.OpenVASP.Transactions.Client platform=nuget version=9.1.0
time="2021-01-28T11:29:54-05:00" level=info msg="Depper publish" name=RealoAPI platform=nuget version=1.0.2
time="2021-01-28T11:29:54-05:00" level=info msg="Depper publish" name=Mosaik.FrontEnd.Topics platform=nuget version=0.0.15494
time="2021-01-28T11:29:54-05:00" level=info msg="Depper publish" name=Slack.Webhooks.Integration platform=nuget version=1.0.0
...
```
We can view [this website …

Add ingestor for Nuget.

---

ingestors/maven_central.go
ingestors/ttler.go
main.go
publishers/pipeline.go
publishers/publisher.go
publishers/publishing.go
publishers/sidekiq.go

Also moves the deduping logic to the publishing pipeline.

Allow ingestors to define their own TTL

---

ingestors/packagist.go
main.go

* sync the latest 40 recently-released releases' packages
* sync the latest 40 recently-released packages
* sync the latest 40 recently-released releases 
Explanation: I don't think we need to ingest recently-releases packages too -- we'll get those when their first versions are published?
e.g.
```
...
time="2021-01-29T12:30:00-05:00" level=info msg="Depper publish" name=baraja-core/doctrine-mail-message platform=packagist version=v1.1.1
time="2021-01-29T12:30:00-05:00" level=info msg="Depper publish" name=dizatech/pacman platform=packagist version=v1.0.6
time="2021-01-29T12:30:00-05:00" level=info msg="Depper publish" name=uspdev/replicado platform=packagist version=1.6.3
...
```
NB the Packagist feed does *not* include development releases.

Adds Packagist ingestor.

---

ingestors/pypi_rss.go

This is the updates bit of the ingestion. I'm going to add the new packages bit next, but since it didn't include a version, I'm going to get a little more complex and call out to each of the items to get the versions available before sending them off to the publisher.
I'm sneaking in the removal of the npm migration thing from the last PR, it's pretty innocuous.

Added PyPI rss update stream ingestor

---

ingestors/bookmarks.go
ingestors/pypi_rss.go
main.go

This got a little fancier than perhaps it needed to be, but I think the bookmark stuff is worthwhile, and it makes me feel more comfortable about hitting PyPI every minute.
The package feed doesn't give us a version:
```
<item>
<title>fab-addon-ferrisconsul added to PyPI</title>
<link>https://pypi.org/project/fab-addon-ferrisconsul/</link>
<guid>https://pypi.org/project/fab-addon-ferrisconsul/</guid>
<description>FAB addon for managing Consul configurations</description>
<author>nikola.gajin@ferrislabs.net</author>
<pubDate>Tue, 02 Feb 2021 15:13:23 GMT</pubDate>
</item>
```
But the release feed does
```
<item>
<title>0.0.1</title>
<link>https://pypi.org/project/fab-addon-ferrisconsul/0.0.1/</link>
<description>FAB addon for managing Consul configurations</description> …
```

Added package release feed / release feed bits of PyPI rss ingestor

---

ingestors/maven.go

I wanted to use a bookmark but we thought of some edge cases where updated_at could be slightly off if a package release slipped in while an index was being created. This achieves the same basic goal of not redoing work since we will replace all package versions in our maven services approx every 7 days. This gives us a bit of a buffer.

Bump maven ttl to 10 days

---

go.mod
ingestors/bookmarks.go
ingestors/drupal.go
main.go

Adds ingestor for Drupal repo, which is a repository of Composer packages:
```
...
time="2021-08-28T00:51:24-04:00" level=info msg="Depper publish" created="2021-08-23 10:03:01 +0000 +0000" name=date_augmenter platform=drupal version=1.0.0-rc1
time="2021-08-28T00:51:24-04:00" level=info msg="Depper publish" created="2021-08-23 07:06:12 +0000 +0000" name=cypress platform=drupal version=2.3.18
time="2021-08-28T00:51:24-04:00" level=info msg="Depper publish" created="2021-08-23 06:53:52 +0000 +0000" name=phoney platform=drupal version=1.0.0
time="2021-08-28T00:51:24-04:00" level=info msg="Depper publish" created="2021-08-23 06:50:26 +0000 +0000" name=phoney platform=drupal version=1.0.x-dev
time="2021-08-28T00:51:24-04:00" level=info msg="Depper publish" created="2021-08-23 05:35:58 +0000 …
```

Add Drupal ingestor

---

main.go

This specific bookmark (stored in redis) is raising an encoding exception:
`depper:bookmark:pypiXmlRpc = "2021-12-11T00:05:11Z"`

Temp disable pypi xml rpc ingestor until we can debug.

---

ingestors/pypi_xml_rpc.go
main.go

The Pypi XML RPC ingestor picked up some bad data in the "changelog" method at this timestamp: `"2021-12-11T00:05:11Z"`:
`<value><string>add source file azure-agrifood-farming-100.10.7.tar.gz</string></value>`
If you inspect the original fragment, there are some bytes that are probably ANSI deletion codes: `ESC [ m ESC K`. 
Since these aren't valid XML bytes, [go rejects them and raises an error](https://github.com/golang/go/blob/1540239f48f6beaa1cae6b34d00d74860366da7d/src/encoding/xml/xml.go#L1138).
This change just ignores the whole page if we run into this, since grabbing the page *except* the invalid part seems like a can of worms.

Re-enable pypi xmlrpc ingestor and skip bad bytes in XML.

---

ingestors/go.go

Placeholder to ignore this go module until we fix it later.

Temporarily ignore go-micro.dev/v4

---

ingestors/npm.go

The `"stream error: stream ID 123; INTERNAL_ERROR"` has consistently been a pain, but if I switch the options to use a heartbeat instead of timeout, the problem disappears for me locally at least.

Try to fix stream error in NPM ingestor using heartbeat option.

---

go.mod
go.sum
main.go

This configures depper to always wrap fields in quotes inside logrus' structured logs, so that the fields can be properly indexed:
`time="2022-11-30T19:01:56-07:00" level=info msg="Depper publish" created="2022-12-01 01:59:42.49 +0000 UTC" name=@some/package platform=npm version=1.4.2`
`time="2022-11-30T19:01:56-07:00" level=info msg="Depper publish" created="2022-12-01 01:59:42.49 +0000 UTC" name="@some/package" platform="npm" version="1.4.2"`

Force quoting on structured log fields 

---

ingestors/maven.go
ingestors/maven_parser.go

Currently depper's maven ingestors fetch packages like this:
1) get the bookmark from redis (or default to 7 years ago), e.g. `"depper:bookmark:maven_mavencentral"`
2) fetch the list of recent packages (which is probably just the latest incremental index from the nexus indexers), e.g. `https://maven.libraries.io/mavenCentral/recent`
3) return any releases from that response that have a createdAt *after* the bookmark date
4) set the bookmark in redis to the newest createdAt from those packages
5) pipeline.go: this publishes any releases that don't have a TTL redis key, e.g. `"depper:ingest:maven_mavencentral:org.apache.struts:struts2-core:6.1.1"`
So we basically have two mechanisms of deduping packages depper's published: the bookmark and the TTL.
The bookmark seems to be problematic …

Remove bookmark usage in maven ingestors, in favor of just TTL.

---

data/package_version.go
go.mod
ingestors/cargo.go
ingestors/conda_parser.go
ingestors/drupal.go
ingestors/elm.go
ingestors/go.go
ingestors/maven_parser.go
ingestors/npm.go
ingestors/nuget.go
ingestors/packagist.go
ingestors/pypi_rss.go
ingestors/pypi_xml_rpc.go
ingestors/rubygems.go
main.go
publishers/logging_publisher.go

```time="2023-02-02T13:21:13-07:00" level="info" msg="Depper publish" created="2017-07-27 00:58:14.264 -0700 MST" discoveryLag="174226973683" name="org.springframework.boot:spring-boot-devtools-tests" platform="maven_springlibs" version="1.5.6.RELEASE"```
Also: some linting and go version bump.

Adds a "discoveryLag" log field to know explicit lag between creation+discovery

---

ingestors/rubygems.go

These errors come along from the rubygems ingestor sometimes. We don't have any idea what the feed response was in those cases, so this moves the error logging inside our line-by-line callback so we know where the parsing went wrong:
```
*errors.errorStringmain.go:76
Unknown value type
*errors.errorString Unknown value type 
github.com/sirupsen/logrus@v1.9.0/entry.go:304 (*Entry).Log
/app/ingestors/rubygems.go:72 (*RubyGems).ingestURL
/app/ingestors/rubygems.go:32 (*RubyGems).Ingest
main.go:76 (*Depper).registerIngestor.func1
github.com/robfig/cron/v3@v3.0.1/cron.go:136 FuncJob.Run
github.com/robfig/cron/v3@v3.0.1/cron.go:312 (*Cron).startJob.func1
```

Log rubygems feed error earlier so we have more diagnostic data.

---

.circleci/config.yml
ingestors/pypi_xml_rpc.go
ingestors/pypi_xml_rpc_test.go

previously the PyPiXmlRpc ingestor used the `changelog` endpoint, which accepted a timestamp int as an arg. But now we're using [`changelog_since_serial`, which takes a serial int as an arg](https://warehouse.pypa.io/api-reference/xml-rpc.html#changelog-since-serial-since-serial). The serial int is passed along with every event, so we can parse that and store it as the bookmark now, instead of the timestamp.
(followup to https://github.com/librariesio/depper/pull/74)

PyPiXmlRpc: update response handling to use serial instead of timestamp

---

.gitignore
ingestors/cargo.go

Cargo ingestion is currently broken but we aren't logging anything. Local investigation shows errors in the API response but those are hidden on production. This PR would add a handler for the `errors` key in the API response, log out each detail message, and return an Error object from the ingestor.

Log Out Error Messages from Cargo API

---

ingestors/cargo.go
ingestors/constants.go

It looks like https://github.com/rust-lang/crates.io/blob/9c7302bdc16c6a4d917cf5929c4e6edd74a5da9a/src/middleware/block_traffic.rs#L45 made it so that they block requests based on headers and ip
https://crates.io/data-access#api suggests adding a useful user agent string, so adding it here.

Fix broken Cargo ingestor

---

main.go

Rather than break the entire ingestion pipeline, let's just skip drupal for now

drupal ingestor is returning a 403, turn it off while we investigate

---

ingestors/cocoapods.go
main.go

Cocoapods releases are reflected by commits to the cocoapods/Specs repo in github. So just parse
that RSS feed and notify accordingly

Add support to watch for new cocoapods releases

---

ingestors/cpan.go
ingestors/hackage.go
ingestors/hex.go
ingestors/pub.go
main.go

Final ecosystems from dispatch. Note that I shifted CPAN to use their RSS feed as it should be lighterweight than calling their elasticsearch endpoint.

Add ingestors for cpan, hackage, pub, and hex

---

ingestors/go.go

* Go ingestor:
* add persisted bookmarking
* previously, we would use "1 day ago" as the in-memory bookmark, whenever Depper restarts. But we currently need to do a backfill, so now's a good time to add persisted bookmarks (based on the "Timestamp" we get back from index.golang.org)
* start logging pseudoversions again
* these were disabled in 2022 before a lot of our Go code was cleaned up and wrangled: https://github.com/librariesio/depper/pull/57 ... but it's quite common for v0 Go Modules to be required from other packages, so Libraries needs to know about packages that only have pseudoversions. For example, here's a library that's required by another OSS package but doesn't have v1+ versions, as of writing: https://pkg.go.dev/github.com/charmbracelet/x/exp/golden@v0.0.0-20250107110353 …

Go ingestor changes

---

.circleci/config.yml
README.md

* `golangci-lint` 1.57.2 ~> 1.63.4
* add lint instructions to README
this version of the linter adds more support for autofixing (35 linters support it in total now)

Update linter to latest, and add a doc.

---

README.md
ingestors/bookmarks.go
ingestors/cargo.go
ingestors/elm.go
ingestors/go.go
ingestors/hackage.go
ingestors/hex.go
ingestors/interfaces.go
ingestors/npm.go
ingestors/nuget.go
ingestors/pub.go
ingestors/rubygems.go
main.go
publishers/sidekiq.go

The main goal here is to add better DD tracing insights, to make better guesses about what is SIGKILL'ing the process occasionally: 
* rename `Ingestor` interface to `PollingIngestor`, and rename `Namer` interface to be the new `Ingestor` interface
* define `Name()` functions on remaining ingestors that don't have it
* set an `"ingestor"` tag on DD spans, using the `Name()` functions
* wrap a new DD span around the the batch publishing of ingestor releases too

DD spans: include "name" tag 

---

ingestors/npm.go

NPM's couchdb replica is currently down (503'ing), so depper is restarting every few minutes when the NPM ingestor tries to connect and does a fatal log:
This prevents the restarts by adding an initial connection loop for NPM's ingestor. If the NPM service is down, we'll wait 5 minutes and try again:

If NPM is unavailable when connecting, wait 5 minutes and try again.

---

main.go

someone is doing supply chain research on cocoapods and publishing a ridiciulous number of releases which is overwhelming the cocoapods git repo

turn off cocoapods temporarily
